# --------------------------------------------------------------------------
# Substitutions
#
# These are substitutions as used by the configuration packages from below.
# You can uncomment and update the ones that you want to modify.
# --------------------------------------------------------------------------

substitutions:
  name: truenas-power
  friendly_name: truenas-power
  device_name: truenas-power


esphome:
  name: ${name}

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_encryption_key_server_power

ota:
  password: !secret ota_password_server_power
  platform: esphome

wifi:
  ssid: !secret wifi_ssid_fritz
  password: !secret wifi_password_fritz

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}_fallback
    password: !secret ap_password

captive_portal:

switch:
  - platform: gpio
    name: "NAS Power Toggle"
    icon: "mdi:electric-switch"
    pin: 
      number: D1   # Power button output pin
      allow_other_uses: true
    id: power_short_press
    inverted: no
    on_turn_on:
    - delay: 200ms
    - switch.turn_off: power_short_press
    


  - platform: gpio
    name: "NAS HARD POWER OFF"
    icon: "mdi:electric-switch"
    pin: 
      number: D1   # Power button output pin
      allow_other_uses: true
    id: power_long_press
    inverted: no
    on_turn_on:
    - delay: 3500ms
    - switch.turn_off: power_long_press